INSERT INTO Rule VALUES (1,'前に1マス進む');
INSERT INTO Rule VALUES (2,'前に何マスでも進む');
INSERT INTO Rule VALUES (3,'右に1マス進む');
INSERT INTO Rule VALUES (4,'右に何マスでも進む');
INSERT INTO Rule VALUES (5,'左に1マス進む');
INSERT INTO Rule VALUES (6,'左に何マスでも進む');
INSERT INTO Rule VALUES (7,'後ろに1マス進む');
INSERT INTO Rule VALUES (8,'後ろに何マスでも進む');
INSERT INTO Rule VALUES (9,'左前に1マス進む');
INSERT INTO Rule VALUES (10,'左前に何マスでも進む');
INSERT INTO Rule VALUES (11,'右前に1マス進む');
INSERT INTO Rule VALUES (12,'右前に何マスでも進む');
INSERT INTO Rule VALUES (13,'左後ろに1マス進む');
INSERT INTO Rule VALUES (14,'左後ろに何マスでも進む');
INSERT INTO Rule VALUES (15,'右後ろに1マス進む');
INSERT INTO Rule VALUES (16,'右後ろに何マスでも進む');
INSERT INTO koma VALUES (1,'歩');
INSERT INTO koma VALUES (2,'香');
INSERT INTO koma VALUES (3,'桂');
INSERT INTO koma VALUES (4,'銀');
INSERT INTO koma VALUES (5,'金');
INSERT INTO koma VALUES (6,'角');
INSERT INTO koma VALUES (7,'飛');
INSERT INTO koma VALUES (8,'王');
INSERT INTO Deck (name, sfen) VALUES ('sample', '5/2[8]2');
INSERT INTO KomaRule (koma_id, rule_id) VALUES (1, 1);
INSERT INTO KomaRule (koma_id, rule_id) VALUES (4, 1);
INSERT INTO KomaRule (koma_id, rule_id) VALUES (4, 9);
INSERT INTO KomaRule (koma_id, rule_id) VALUES (4, 11);
INSERT INTO KomaRule (koma_id, rule_id) VALUES (4, 13);
INSERT INTO KomaRule (koma_id, rule_id) VALUES (4, 15);
