INSERT INTO koma VALUES (0,'王将', -1);
INSERT INTO koma VALUES (1,'歩兵', 8);
INSERT INTO koma VALUES (2,'香車', 9);
INSERT INTO koma VALUES (3,'桂馬', 10);
INSERT INTO koma VALUES (4,'銀将', 11);
INSERT INTO koma VALUES (5,'金将', -1);
INSERT INTO koma VALUES (6,'角行', 12);
INSERT INTO koma VALUES (7,'飛車', 13);
INSERT INTO koma VALUES (8,'と金', -1);
INSERT INTO koma VALUES (9,'成香', -1);
INSERT INTO koma VALUES (10,'成桂', -1);
INSERT INTO koma VALUES (11,'成銀', -1);
INSERT INTO koma VALUES (12,'馬', -1);
INSERT INTO koma VALUES (13,'龍', -1);


INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'DOWN_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (0, 'DOWN_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (1, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (2, 'LINE_UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (3, 'JUMP_UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (3, 'JUMP_UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (4, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (4, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (4, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (4, 'DOWN_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (4, 'DOWN_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (5, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (5, 'DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (5, 'LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (5, 'RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (5, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (5, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (6, 'LINE_UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (6, 'LINE_UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (6, 'LINE_DOWN_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (6, 'LINE_DOWN_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (7, 'LINE_UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (7, 'LINE_DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (7, 'LINE_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (7, 'LINE_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (8, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (8, 'DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (8, 'LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (8, 'RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (8, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (8, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (9, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (9, 'DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (9, 'LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (9, 'RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (9, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (9, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (10, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (10, 'DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (10, 'LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (10, 'RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (10, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (10, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (11, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (11, 'DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (11, 'LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (11, 'RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (11, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (11, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'LINE_UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'LINE_UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'LINE_DOWN_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (12, 'LINE_DOWN_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'UP_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'UP_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'DOWN_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'DOWN_RIGHT');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'LINE_UP');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'LINE_DOWN');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'LINE_LEFT');
INSERT INTO KomaRule (koma_id, rule) VALUES (13, 'LINE_RIGHT');

INSERT INTO Deck (name, sfen) VALUES ('sample', '5/2[0]2');
