CREATE TABLE koma(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  skill VARCHAR(50) DEFAULT NULL,
  update_koma INT DEFAULT -1
);

CREATE TABLE KomaRule(
  id INT PRIMARY KEY AUTO_INCREMENT,
  koma_id INT,
  rule VARCHAR(50),
  FOREIGN KEY (koma_id) REFERENCES koma(id)
);

CREATE TABLE Deck(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  sfen VARCHAR(255)
);
