CREATE TABLE koma(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  type VARCHAR(1)
);

CREATE TABLE Deck(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  sfen VARCHAR(255)
);
